import { Routes } from '@angular/router';
import { Homepage } from './homepage/homepage';
import { DashboardPage } from './dashboard-page/dashboard-page';
import { SignupPage } from './signup-page/signup-page';
import { LoginPage } from './login-page/login-page';
import { MarketplacePage } from './marketplace-page/marketplace-page';
import { ChatPage } from './chat-page/chat-page';
import { ContactPage } from './contact-page/contact-page';
import { ForgotPasswordPage } from './forgot-password-page/forgot-password-page';
import { ViewDetailPage } from './view-detail-page/view-detail-page';
import { CartPage } from './cart-page/cart-page';
import { PreCheckoutPage } from './pre-checkout-page/pre-checkout-page';
import { AddProduct } from './add-product/add-product';
import { EditPost } from './edit-post/edit-post';
import { AboutUs } from './about-us/about-us';
import { SellerPage } from './seller-page/seller-page';
import { SellerCreatePage } from './seller-create-page/seller-create-page';
import { TermAndConditionPage } from './term-and-condition-page/term-and-condition-page';
import { SellerStorePage } from './seller-store-page/seller-store-page';
import { ProfilePage } from './profile-page/profile-page';
import { SettingPage } from './setting-page/setting-page';
import { SecurityPage } from './security-page/security-page';
import { NotificationPage } from './notification-page/notification-page';
import { BillingPage } from './billing-page/billing-page';
import { VerificationPage } from './verification-page/verification-page';

export const routes: Routes = [
  { path: '', component: Homepage },
  { path: 'dashboard-page', component: DashboardPage },
  { path: 'signup-page', component: SignupPage },
  { path: 'login-page', component: LoginPage },
  { path: 'marketplace-page', component: MarketplacePage },
  { path: 'chat-page', component: ChatPage },
  { path: 'contact-page', component: ContactPage },
  { path: 'view-detail-page/:id', component: ViewDetailPage },
  { path: 'forgotPassword-page', component: ForgotPasswordPage },
  { path: 'pre-checkout-page', component: PreCheckoutPage },
  { path: 'add-product-page', component: AddProduct },
  { path: 'add-product-page', component: AddProduct },
  { path: 'product-edit-page/:id', component: EditPost },
  { path: 'cart-page', component: CartPage },
  { path: 'about-us-page', component: AboutUs },
  { path: 'seller-page', component: SellerPage },
  { path: 'seller-create-page', component: SellerCreatePage },
  { path: 'term-and-condition-page', component: TermAndConditionPage },
  { path: 'seller-store-page', component: SellerStorePage },
  { path: 'profile-page', component: ProfilePage },
  { path: 'setting-page', component: SettingPage },
  { path: 'security-page', component: SecurityPage },
  { path: 'notification-page', component: NotificationPage },
  { path: 'billing-page', component: BillingPage },
  { path: 'verification-page', component: VerificationPage },
];
